# Generated by Django 4.0.6 on 2022-07-24 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='説明')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='カバー')),
                ('finish_count', models.IntegerField(default=0, verbose_name='周回')),
                ('postData', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repercisebook.book')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000, verbose_name='設問')),
                ('answer', models.CharField(max_length=255, verbose_name='解答')),
                ('explanation', models.TextField(blank=True, max_length=1000, null=True, verbose_name='解説')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解したか')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repercisebook.section')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='repercisebook.tag', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
