# Generated by Django 4.0.6 on 2022-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repercisebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='repercisebook.tag', verbose_name='タグ'),
        ),
    ]
