# Generated by Django 4.0.6 on 2022-07-31 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repercisebook', '0002_alter_book_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='orderNum',
            field=models.IntegerField(default=1000, verbose_name='順序'),
        ),
        migrations.AlterField(
            model_name='section',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='repercisebook.book'),
        ),
    ]
