# Generated by Django 4.0.6 on 2022-08-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repercisebook', '0003_section_ordernum_alter_section_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='orderNum',
            field=models.IntegerField(default=1000, verbose_name='順序'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='repercisebook.section'),
        ),
    ]
