# Generated by Django 4.0.6 on 2022-08-10 16:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repercisebook', '0004_problem_ordernum_alter_problem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='カバー'),
        ),
    ]
