# Generated by Django 4.0.6 on 2022-08-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repercisebook', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='カバー'),
        ),
    ]
